### ISSUE TITLE
Origins are always wildcards

### ISSUE THREAD

**Issue by werbitzky** [bryanjos/plug_cors#11]
In the case where an origin is not a wildcard, the library still treats it like a wildcard, using String.contains? function to validate the origin.
When allowing the origin `google.com` every subdomain, e.g. `*.google.com` would also be valid, hence it would be a false positive

https://github.com/bryanjos/plug_cors/blob/master/lib/plug_cors/preflight.ex#L34

```elixir
  defp is_origin_allowed?(origin_to_test, allowed_origin) do
    case allowed_origin do
      "*" ->
        true
      "*." <> domain ->
        String.contains?(origin_to_test, domain)
      _ -> 
        String.contains?(origin_to_test, allowed_origin)
    end
  end
```

**Comment by bryanjos** [comment]
Ah yes, you are correct. I will update that

**Comment by bryanjos** [comment]
@werbitzky I take a look at #13 for issues #11 and #12. It should resolve the issues.

**Comment by werbitzky** [comment]
@bryanjos  Great, thanks a lot!

**Comment by bryanjos** [comment]
@werbitzky thanks for bringing up these issues. I'll close these now and update the version in hex between today and tomorrow.
