### ISSUE TITLE
Consider allowing configuration via elixir config.

### ISSUE THREAD

**Issue by jeregrine** [bryanjos/plug_cors#4]

**Comment by bryanjos** [comment]
That sounds reasonable. I could probably give it some more thought and get it done sometime later in the week

**Comment by bryanjos** [comment]
Had some free time a decided to just do it now. You can now use the configuration in version 0.7.0.

You can define the config section like so:

```elixir
  config :plug_cors,
    origins: ["test.origin.test", "*.domain.com"],
    methods: ["GET", "POST"],
    headers: ["Authorization"]
```

and then define the plug like so:

```elixir
plug PlugCors
```

You can still define parameters when defining the plug and if set those will override the values in the config
