### ISSUE TITLE
Router returns 404 for HTTP OPTIONS

### ISSUE THREAD

**Issue by house9** [bryanjos/plug_cors#8]
I am a total Elixir/Phoenix newbie so it is possible I have just misconfigured this Plug. Any help would be appreciated.

Phoenix Version: 0.13.1
PlugCors Version: 0.7.1

All requests are returning HTTP 404 for OPTIONS requests

```
curl -v -X OPTIONS http://localhost:4000/api/projects -o /dev/null

* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* connect to ::1 port 4000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4000 (#0)
> OPTIONS /api/projects HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:4000
> Accept: */*
>
< HTTP/1.1 404 Not Found
< connection: keep-alive
* Server Cowboy is not blacklisted
< server: Cowboy
< date: Wed, 20 May 2015 17:22:12 GMT
< content-length: 37070
< cache-control: max-age=0, private, must-revalidate
< content-type: text/html; charset=utf-8
<
{ [data not shown]
100 37070  100 37070    0     0  1994k      0 --:--:-- --:--:-- --:--:-- 2011k
* Connection #0 to host localhost left intact
```

The router code

```
defmodule OhCrud.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug PlugCors, origins: ["*"]
  end

  scope "/api", OhCrud do
    pipe_through :api

    resources "/projects", Api.ProjectController
  end
end
```

I came across https://github.com/jeffweiss/todobackend-phoenix where cors is manually implemented and an `options` action is added to each controller which is great for that example application, however my understanding is that `PlugCors` code should get invoked before the router tried to invoke a controller action, is it possible that a newer version of phoenix has caused an issue?

**Comment by bryanjos** [comment]
Looks like you would have to define it above the router for it to work. For instance:

```elixir
defmodule OhCrud.Endpoint do
  #the rest of the plugs

  plug PlugCors, origins: ["*"]
  plug :router, OhCrud.Router
end
```

I think by the time it hits the router, the router is already trying to find the route and since it can't find it, send a 404.

**Comment by bryanjos** [comment]
I'll update the docs to make it clearer how to use with Phoenix

**Comment by house9** [comment]
Still not working for me, I'm probably missing something really simple?

put together this sample application: https://github.com/house9/sample_phoenix_plug_cors 
it is literally just a new phoenix application with PlugCors added and returns 404 when hitting / with OPTIONS

**Comment by bryanjos** [comment]
There is something going on, but I haven't figured out what yet. It looks like some where along the line the cors headers put on the response aren't making it all the way through.

For the request you are doing with curl, it's going to return 404 because PlugCors only intercepts OPTIONS requests with the "access-control-request-method" header.

**Comment by bryanjos** [comment]
I checked it out and things should be working correctly. As I mentioned, any OPTIONS requests without the "access-control-request-method" header are going to be let through the plug without  being touched. 

I'll make a PR to the repo you have above to give an example on what I did.

**Comment by house9** [comment]
@bryanjos - Thanks a ton for all of your help!

Using curl turned out to be very misleading, I could never get it to work correctly; even after adding the headers it would return 403; I am using it from a toy angular application anyhow and that is now working as expected. :)

There is one interesting gotcha:

* `origins: "*"` works
* `origins: ["*"]` fails the pattern match at https://github.com/bryanjos/plug_cors/blob/master/lib/plug_cors/preflight.ex#L26 
  * this is default, but I kept changing it from `["localhost"]` to `["*"]` while debugging
* `origins: ["example.com", "*"]` fails unless the request is from example.com
  * would never use this in production, but maybe in development during setup?

Let me know if you want a PR for the above edge cases? I could try and put something together later today.

**Comment by bryanjos** [comment]
Awesome! Yes, for that case please make it an issue or a PR if you can.
